## Travis CI configuration
dist: trusty
sudo: false
language: c
branches:
  only:
  - changeling
  - fever
  - master
  - travis
# Test matrix:
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
# How to build:
script: ./bootstrap && ./configure && make check
# Notifications
notifications:
  email:
    - empserver-devel@wolfpackempire.com
  irc: "irc.oftc.net#wolfpack"
